name: StopBucketFill
version: ${project.version}
main: me.noodles.sbf.SBF
authors: [BGHDDevelopment]
website: https://bghddevelopment.com/
commands:
  sbf:
    description: SBF command
    usage: /<command> reload